// Cross-schema test: a NEST replay produced by the REAL adapter must parse with the
// browser player's own parser, and must agree with the source NEST run.
//
// Run: node --test tests/nest.replay.parser.test.mjs
//
// The fixture is generated by tests/fixtures/make_nest_replay_fixture.py through the real
// adapter, and `expected.json` is taken from the NEST RunResult -- NOT from the artifact.
// So these assertions compare the artifact against the run that produced it, rather than
// against itself.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  parseReplay, reconstructWeightsAt, ReplayError,
  REPLAY_SCHEMA_NAME, SUPPORTED_SCHEMA_VERSION,
} from '../frontend/replay.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE = readFileSync(join(HERE, 'fixtures', 'nest_replay_fixture.snn.jsonl'), 'utf-8');
const EXPECTED = JSON.parse(readFileSync(join(HERE, 'fixtures', 'nest_replay_fixture.expected.json'), 'utf-8'));

// ------------------------------------------------------------------ parsing
test('the existing schema-1 parser accepts a NEST replay unchanged', () => {
  const r = parseReplay(FIXTURE);
  assert.equal(r.header.schema, REPLAY_SCHEMA_NAME);
  assert.equal(r.schemaVersion, SUPPORTED_SCHEMA_VERSION);
  assert.ok(r.frames.length > 0);
  assert.ok(r.result, 'final result record parsed');
});

test('topology counts match the canonical 3x3 network', () => {
  const r = parseReplay(FIXTURE);
  assert.equal(r.neuronIds.size, EXPECTED.neuron_count);
  assert.equal(r.synapseIds.size, EXPECTED.synapse_count);
  assert.equal(r.neuronIds.size, 191);
  assert.equal(r.synapseIds.size, 1052);
});

test('initial weights are the frozen NEST weights', () => {
  const r = parseReplay(FIXTURE);
  assert.equal(Object.keys(r.initialWeights).length, EXPECTED.weighted_synapse_count);
});

// -------------------------------------------------------------------- time
test('frame ticks and millisecond times match the source run', () => {
  const r = parseReplay(FIXTURE);
  assert.equal(r.frames.length, EXPECTED.frame_count);
  assert.deepEqual(r.frames.map(f => f.timestep), EXPECTED.frame_ticks);
  assert.deepEqual(r.frames.map(f => f.dynamic.nest.t_ms), EXPECTED.frame_t_ms);
});

test('every frame time is tick * h exactly', () => {
  const r = parseReplay(FIXTURE);
  const h = EXPECTED.resolution_h_ms;
  for (const f of r.frames) {
    const expected = Number((f.timestep * h).toFixed(10));
    assert.equal(f.dynamic.nest.t_ms, expected, `frame ${f.frameIndex}`);
    assert.equal(f.dynamic.nest.resolution_h_ms, h);
  }
});

test('frame timesteps are strictly increasing', () => {
  const r = parseReplay(FIXTURE);
  for (let i = 1; i < r.frames.length; i++)
    assert.ok(r.frames[i].timestep > r.frames[i - 1].timestep);
});

// ------------------------------------------------------------------ spikes
test('the spike multiset round-trips exactly, with no sender lost', () => {
  const r = parseReplay(FIXTURE);
  const got = [];
  for (const f of r.frames) {
    const t = f.dynamic.nest.t_ms;
    for (const n of f.dynamic.neurons) if (n.spiked) got.push([Number(t.toFixed(6)), n.id]);
  }
  const norm = (rows) => rows.map(([t, id]) => `${t}|${id}`).sort();
  // Cortical spikes AND retinal input events: two NEST recorders, one `spiked` flag.
  assert.equal(got.length, EXPECTED.cortical_spike_count + EXPECTED.input_event_count);
  assert.deepEqual(norm(got), norm(EXPECTED.all_events));
});

test('retinal sources light up rather than staying dark', () => {
  // Regression: RGC events are recorded on a separate recorder from cortical spikes, and
  // an earlier adapter never carried them into `spiked`, leaving the whole 9x9 input
  // surface dark in the renderer.
  const r = parseReplay(FIXTURE);
  const rgc = new Set(r.topology.neurons.filter(n => n.archetype === 'rg_source').map(n => n.id));
  assert.equal(rgc.size, 81);
  const lit = new Set();
  for (const f of r.frames)
    for (const n of f.dynamic.neurons) if (n.spiked && rgc.has(n.id)) lit.add(n.id);
  assert.deepEqual([...lit].sort(), EXPECTED.lit_rgc_ids);
  assert.ok(lit.size > 0, 'the driven patch must produce lit retinal cells');
});

test('a lit retinal cell also pulses its feedforward edges', () => {
  const r = parseReplay(FIXTURE);
  const rgc = new Set(r.topology.neurons.filter(n => n.archetype === 'rg_source').map(n => n.id));
  const inputFrames = r.frames.filter(f =>
    f.dynamic.neurons.some(n => n.spiked && rgc.has(n.id)));
  assert.ok(inputFrames.length > 0);
  for (const f of inputFrames)
    assert.ok(f.dynamic.emitted.length > 0,
      'an input volley must pulse its rg_to_column edges, or the input looks disconnected');
});

test('simultaneous winners are all present in the same frame', () => {
  const r = parseReplay(FIXTURE);
  let sawMulti = false;
  for (const f of r.frames) {
    const mult = f.dynamic.nest.winner_multiplicity || {};
    const fired = new Set(f.dynamic.neurons.filter(n => n.spiked).map(n => n.id));
    for (const [col, count] of Object.entries(mult)) {
      if (count > 1) sawMulti = true;
      for (const id of f.dynamic.nest.column_winners[col])
        assert.ok(fired.has(id), `${id} is a declared winner but has no spiked flag`);
    }
  }
  assert.ok(sawMulti,
    'the fixture must contain at least one multi-winner tick -- that is the headline ' +
    'NEST observation and the player must be able to show it');
});

// ------------------------------------------------------------------ honesty
test('unsampled membrane state never arrives as a number', () => {
  const r = parseReplay(FIXTURE);
  for (const f of r.frames) {
    for (const n of f.dynamic.neurons) {
      for (const field of ['potential', 'activation', 'freq', 'refractory']) {
        assert.ok(n[field] == null,
          `${field} must be unknown for a NEST replay, got ${JSON.stringify(n[field])}`);
      }
    }
  }
});

test('the artifact declares what is recorded, derived and unavailable', () => {
  const r = parseReplay(FIXTURE);
  const declared = r.header.recording.state_availability;
  assert.equal(declared.spiked, 'recorded');
  assert.equal(declared.emitted, 'derived');
  assert.equal(declared.potential, 'unavailable');
  for (const f of r.frames)
    assert.deepEqual(f.dynamic.nest.state_availability, declared);
});

test('every node appears in every frame so no state leaks forward', () => {
  const r = parseReplay(FIXTURE);
  for (const f of r.frames)
    assert.equal(f.dynamic.neurons.length, EXPECTED.neuron_count);
});

// ---------------------------------------------------------------- frozen
test('weights are frozen: no changed_synapses, and reconstruction is constant', () => {
  const r = parseReplay(FIXTURE);
  for (const f of r.frames) assert.equal(f.changed.length, 0);
  const first = reconstructWeightsAt(r, r.frames[0].frameIndex);
  const last = reconstructWeightsAt(r, r.frames[r.frames.length - 1].frameIndex);
  assert.equal(first.size, last.size);
  for (const [id, w] of first) assert.equal(last.get(id), w);
  for (const [id, w] of Object.entries(r.initialWeights)) assert.equal(last.get(id), w);
});

// ------------------------------------------------------------- provenance
test('provenance identifies the engine, versions and limitations', () => {
  const r = parseReplay(FIXTURE);
  const p = r.header.nest;
  assert.equal(p.engine, 'nest');
  assert.equal(p.learning_mode, EXPECTED.learning_mode);
  assert.equal(p.mpi_available, EXPECTED.mpi_available);
  assert.equal(p.nest_version, EXPECTED.nest_version);
  assert.equal(p.nestml_version, EXPECTED.nestml_version);
  assert.equal(p.resolution_h_ms, EXPECTED.resolution_h_ms);
  assert.ok(p.git, 'git provenance present');
  assert.ok(p.spec_hash, 'topology hash present');
});

test('the player can tell a NEST replay from a legacy one without sniffing filenames', () => {
  const r = parseReplay(FIXTURE);
  assert.equal(r.header.nest.engine, 'nest');
  assert.equal(r.meta.conditions.engine, 'nest');
  assert.equal(r.meta.conditions.learning, 'frozen');
});

test('the validity envelope travels with the artifact', () => {
  const r = parseReplay(FIXTURE);
  const env = r.topology.nest.validity_envelope;
  assert.equal(env.leak_rate, 0);
  assert.equal(env.persistent_inhibitory_conductance, false);
  assert.ok(r.topology.nest.known_differences.length >= 3);
});

// --------------------------------------------------------- legacy untouched
test('the legacy fixture still parses identically', () => {
  const legacy = readFileSync(join(HERE, 'fixtures', 'replay_fixture.snn.jsonl'), 'utf-8');
  const r = parseReplay(legacy);
  assert.ok(r.frames.length > 0);
  assert.ok(r.checkpoints.length >= 1);
  assert.equal(r.header.nest, undefined, 'a legacy replay carries no NEST provenance');
});

test('a malformed NEST replay is still rejected', () => {
  const broken = FIXTURE.split('\n').slice(1).join('\n');   // drop the header
  assert.throws(() => parseReplay(broken), ReplayError);
});
