"""Read-only live NEST dashboard (Stage B).

A SEPARATE entry point from the production dashboard. It never touches
`backend.simulation.SimulationEngine`, and the production server never imports this.

    .nest-env/bin/uvicorn nest_backend.dashboard_api:app --port 8100

Why this is allowed to exist
++++++++++++++++++++++++++++

The dashboard prompt makes live mode conditional on proving that advancing NEST in finite
observation chunks is indistinguishable from one `Simulate(total)` call.
`experiments/nest_chunked_equivalence.py` proves it: identical spike multisets, node
counters and connection weights at 1, 2 and 4 threads, with chunk boundaries deliberately
landing mid-volley. That evidence is regenerated by
`tests/nest/test_nest_live_server.py`, so this server cannot outlive its own justification.

Boundaries
++++++++++

* NEST owns simulation time, event delivery, delays, buffering and threads.
* Every PyNEST call is serialised through ONE owner in ONE dedicated CHILD PROCESS. NEST's
  kernel is process-global and segfaults if driven from a second thread of a process that
  has already touched it, so isolation is by process, not convention. A lock around the
  pipe means two requests can never be in flight, hence never inside `Simulate()` at once.
* Python executes no neural events and scans no graph; it submits chunks and reads
  recorders.
* Frames are produced by the SAME adapter functions the offline replay uses, so live and
  replay views cannot drift.

The chunk is an **observation cadence**, not a scientific timestep. Playback speed changes
only how often a chunk is submitted -- never `h`, delays, `D`, or stimulus timestamps.
"""
from __future__ import annotations

import asyncio
import threading
from dataclasses import dataclass
from pathlib import Path

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parent.parent
FRONTEND = REPO_ROOT / "frontend"

# Observation cadence, in units of h. 67 ticks at the default h = 0.1 ms is 6.7 ms, which
# never divides the 20 ms presentation interval -- so chunk boundaries land mid-volley,
# which is the condition the equivalence gate exercised.
CHUNK_TICKS = 67


@dataclass
class Command:
    """A unit of work for the single NEST owner."""
    kind: str
    payload: dict


def _owner_main(conn) -> None:
    """The child process body: the ONLY place PyNEST is ever called.

    NEST's kernel is process-global and is not safe to drive from a second Python thread:
    calling `ResetKernel()` off the main thread after the main thread has already used NEST
    segfaults the interpreter (observed, not theorised). Isolating NEST in its own process
    removes the hazard entirely instead of relying on the server never touching it first.
    """
    import sys
    from pathlib import Path as _Path

    sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))

    from nest_backend.engine import Stimulus, build_schedule
    from nest_backend.recording import collect_inputs, collect_spikes
    from nest_backend.replay_adapter import STATE_AVAILABILITY, to_tick
    from nest_backend.topology import NestTiledNetwork, Timescales

    state = {"net": None, "ts": None, "t_ms": 0.0, "spikes_seen": 0,
             "inputs_seen": 0, "patches": {}, "presentations": 24}

    def rebuild(payload):
        ts = Timescales()
        patches = payload.get("patches") or {"1,1": "row 1"}
        parsed = {tuple(int(x) for x in key.split(",")): name
                  for key, name in patches.items()}
        net = NestTiledNetwork(seed=int(payload.get("seed", 1)), timescales=ts,
                               threads=int(payload.get("threads", 1)))
        presentations = int(payload.get("presentations", state["presentations"]))
        net.set_input_schedule(build_schedule(net, Stimulus(parsed), t0=ts.presentation,
                                              period=ts.presentation,
                                              n_presentations=presentations))
        state.update(net=net, ts=ts, t_ms=0.0, spikes_seen=0, inputs_seen=0,
                     patches=dict(patches), presentations=presentations)
        return net.dashboard_topology()

    def delta():
        net, ts = state["net"], state["ts"]
        spikes = collect_spikes(net)[state["spikes_seen"]:]
        inputs = collect_inputs(net)[state["inputs_seen"]:]
        state["spikes_seen"] += len(spikes)
        state["inputs_seen"] += len(inputs)

        fired = sorted({nid for _t, nid in spikes})
        fired_set = set(fired)
        outgoing = net.outgoing_edges()
        winners = {}
        for nid in fired:
            meta = net.node_meta[nid]
            if meta.get("column_role") == "E" and meta.get("column_id"):
                winners.setdefault(meta["column_id"], []).append(nid)

        node_ids = [n["id"] for n in net.spec["nodes"]]
        h = ts.h
        window = int(max(0, (state["t_ms"] - ts.presentation) // ts.presentation))
        shape = net.spec["topology"]["input_shape"]
        return {
            "timestep": to_tick(state["t_ms"], h),
            "running": False,
            "neurons": [{"id": nid, "spiked": nid in fired_set} for nid in node_ids],
            "changed_synapses": [],
            "emitted": sorted({e for nid in fired for e in outgoing.get(nid, ())}),
            "inhibitory_pulses": [],
            "hard_reset_events": [],
            "latency_ties": [],
            "column_winners": {c: {"id": ids[0], "tau": None}
                               for c, ids in winners.items()},
            "input": [0] * (shape["rows"] * shape["cols"]),
            "winner": None,
            "stats": {"total": len(node_ids), "active": None, "firing": len(fired),
                      "firing_rate": None, "winner": None},
            "log": [],
            "nest": {
                "t_ms": state["t_ms"],
                "tick": to_tick(state["t_ms"], h),
                "resolution_h_ms": h,
                "window": window,
                "patches": state["patches"],
                "threads": int(net.manifest()["kernel"]["local_num_threads"]),
                "case": "live",
                "live": True,
                "observation_chunk_ms": round(CHUNK_TICKS * h, 10),
                "spike_events": fired,
                "input_events": sorted({nid for _t, nid in inputs}),
                "column_winners": {c: list(ids) for c, ids in winners.items()},
                "winner_multiplicity": {c: len(ids) for c, ids in winners.items()},
                "state_availability": STATE_AVAILABILITY,
                "new_spikes": [{"t": t, "id": nid} for t, nid in spikes],
            },
        }

    topology_cache = rebuild({})
    conn.send({"ok": True, "data": {"ready": True}})

    while True:
        try:
            command = conn.recv()
        except EOFError:
            return
        kind, payload = command.get("kind"), command.get("payload", {})
        try:
            if kind == "shutdown":
                conn.send({"ok": True, "data": {}})
                return
            if kind == "topology":
                data = topology_cache
            elif kind == "reset" or kind == "set_pattern":
                if kind == "set_pattern":
                    payload = {"patches": {f"{payload.get('row', 1)},{payload.get('col', 1)}":
                                           payload.get("pattern", "row 1")}}
                topology_cache = rebuild(payload)
                data = topology_cache
            elif kind == "step":
                chunk = round(CHUNK_TICKS * state["ts"].h, 10)
                state["net"].simulate(chunk)
                state["t_ms"] = round(state["t_ms"] + chunk, 10)
                data = delta()
            elif kind == "delta":
                data = delta()
            else:
                raise ValueError(f"unknown command {kind!r}")
            conn.send({"ok": True, "data": data})
        except Exception as exc:
            conn.send({"ok": False, "error": f"{type(exc).__name__}: {exc}"})


class NestOwner:
    """Single-owner proxy to the NEST child process.

    A lock guarantees strict command serialisation: two requests can never be in flight
    on the pipe at once, so NEST is never entered concurrently. The child is the only
    process that imports or calls PyNEST.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._proc = None
        self._conn = None
        self.error: str | None = None

    def start(self) -> None:
        import multiprocessing as mp

        ctx = mp.get_context("spawn")
        parent, child = ctx.Pipe()
        self._proc = ctx.Process(target=_owner_main, args=(child,), daemon=True,
                                 name="nest-owner")
        self._proc.start()
        child.close()
        self._conn = parent
        try:
            first = self._conn.recv()
            if not first.get("ok"):
                self.error = first.get("error")
        except Exception as exc:
            self.error = f"{type(exc).__name__}: {exc}"

    def submit(self, kind: str, payload: dict | None = None, timeout: float = 180.0) -> dict:
        if self.error:
            raise RuntimeError(self.error)
        with self._lock:
            self._conn.send({"kind": kind, "payload": payload or {}})
            if not self._conn.poll(timeout):
                raise TimeoutError(f"NEST owner did not answer {kind!r} within {timeout}s")
            result = self._conn.recv()
        if not result.get("ok"):
            raise RuntimeError(result.get("error", "unknown NEST owner failure"))
        return result.get("data", {})

    def stop(self) -> None:
        if self._proc and self._proc.is_alive():
            try:
                self.submit("shutdown", timeout=10)
            except Exception:
                pass
            self._proc.join(timeout=5)
            if self._proc.is_alive():
                self._proc.terminate()


owner = NestOwner()
app = FastAPI(title="NEST Dashboard (read-only live)")


class PatternBody(BaseModel):
    pattern: str
    row: int = 1
    col: int = 1


@app.on_event("startup")
async def _startup() -> None:
    await asyncio.get_running_loop().run_in_executor(None, owner.start)


@app.on_event("shutdown")
async def _shutdown() -> None:
    owner.stop()


def _run(kind: str, payload: dict | None = None):
    return asyncio.get_running_loop().run_in_executor(
        None, lambda: owner.submit(kind, payload))


@app.get("/api/nest/info")
async def info():
    """Identifies this server as NEST LIVE, and states what it will not do."""
    return {
        "engine": "nest",
        "mode": "live",
        "read_only": True,
        "observation_chunk_ticks": CHUNK_TICKS,
        "learning": "frozen",
        "mpi_available": False,
        "unsupported": {
            "topology_editing": "not available in the NEST prototype",
            "weight_mutation": "weights are frozen static_synapse values",
            "learning_controls": "learning is not integrated into the 3x3 runner",
            "branch_from_replay": "NEST branching semantics are undefined",
            "reseed": "use reset, which rebuilds the same seeded network",
            "stimulation_in_the_past": "NEST has already delivered those timestamps",
        },
    }


@app.get("/api/state")
async def state():
    if owner.error:
        return JSONResponse({"error": owner.error}, status_code=500)
    topology = await _run("topology")
    return {"topology": topology, "dynamic": await _run("delta")}


@app.post("/api/step")
async def step():
    return {"dynamic": await _run("step")}


@app.post("/api/reset")
async def reset():
    topology = await _run("reset")
    return {"topology": topology, "dynamic": await _run("delta")}


@app.post("/api/pattern")
async def pattern(body: PatternBody):
    topology = await _run("set_pattern", body.model_dump())
    return {
        "topology": topology,
        "dynamic": await _run("delta"),
        "note": ("A pattern change deterministically REBUILDS the seeded network. NEST has "
                 "already delivered the earlier schedule, and rewriting a generator's past "
                 "would change what was already simulated."),
    }


# Controls that would mutate a NEST run are refused explicitly rather than silently
# routed into the legacy Python engine.
for _blocked, _reason in (
    ("/api/weight", "weights are frozen in the NEST prototype"),
    ("/api/reseed", "use /api/reset, which rebuilds the same seeded network"),
    ("/api/topology", "topology editing is not available for the NEST prototype"),
):
    def _make(reason: str):
        async def _refuse():
            return JSONResponse({"error": reason, "engine": "nest"}, status_code=409)
        return _refuse
    app.post(_blocked)(_make(_reason))


@app.websocket("/ws")
async def ws(socket: WebSocket) -> None:
    """Stream observation frames.

    A reconnecting client receives the current topology and ONE current dynamic snapshot,
    never an unbounded replay of the whole live session.
    """
    await socket.accept()
    try:
        topology = await _run("topology")
        await socket.send_json({"type": "topology", "data": topology})
        await socket.send_json({"type": "dynamic", "data": await _run("delta")})

        running = False
        interval = 0.25
        while True:
            try:
                message = await asyncio.wait_for(socket.receive_json(), timeout=interval)
                action = message.get("action")
                if action == "start":
                    running = True
                elif action == "pause":
                    running = False
                elif action == "step":
                    await socket.send_json({"type": "dynamic", "data": await _run("step")})
                elif action == "speed":
                    # Wall-clock viewing cadence ONLY. It never changes h, delays, D or
                    # any stimulus timestamp.
                    interval = max(0.02, min(2.0, float(message.get("interval", 0.25))))
            except asyncio.TimeoutError:
                pass
            if running:
                await socket.send_json({"type": "dynamic", "data": await _run("step")})
    except WebSocketDisconnect:
        return


if FRONTEND.is_dir():
    app.mount("/", StaticFiles(directory=str(FRONTEND), html=True), name="frontend")
